### ISSUE TITLE
Downloadable PDF version of the MOT checklist

### ISSUE THREAD

**Issue by dpoulson** [Droid-Builder-Web-Team/db_mot#136]
From the MOT Info page for each test type, have a pdf download available for off line checking incase of portal issues (broken, no network, etc.)

**Comment by RobHowdle** [comment]
I'll take this one if you like. Just done this at work ha.

**Comment by dpoulson** [comment]
Sure. Theres already some PDF packages installed for downloading the cover note and info sheet.

**Comment by dpoulson** [comment]
Finished off the work in the latest commit, so I can print off copies for the weekend.
