### ISSUE TITLE
On profile page achievements text breaks out of box

### ISSUE THREAD

**Issue by dpoulson** [Droid-Builder-Web-Team/db_mot#146]
At certain page widths, the achievements text will break out of its box.

**Comment by dpoulson** [comment]
![Screenshot_2021-07-13_23-23-53](https://user-images.githubusercontent.com/601921/125533043-e399f02d-28f9-437c-83aa-0303787aebc7.png)

**Comment by RobHowdle** [comment]
Completed. Bootstrap specific col sizing was needed for various device sizes.
