### ISSUE TITLE
Partrun payment options.

### ISSUE THREAD

**Issue by dpoulson** [Droid-Builder-Web-Team/db_mot#177]
When creating a part run, let the runner define the payment option, maybe from a dropdown:

Web link
Paypal address (and/or paypal.me)
Email them

Then we can properly format the link.

**Comment by RobHowdle** [comment]
Perhaps it would be a better idea to do checkboxes instead as the part runner may offer multiple payment forms to be more flexible and we can return an array as a list. Would this be a separate table field or just added into the description? Ideally I'd like to keep the description purely for descriptions as if we start adding in other fields into the description it defeats the whole point.
