### ISSUE TITLE
Fix styling on datatables

### ISSUE THREAD

**Issue by dpoulson** [Droid-Builder-Web-Team/db_mot#190]
Page numbers have no styling and hard to hit with fat fingers on a mobile.

**Comment by dpoulson** [comment]
Or, totally overhaul the datatables stuff. :P

**Comment by RobHowdle** [comment]
![Screenshot from 2022-01-17 20-46-52](https://user-images.githubusercontent.com/43747640/149836241-505d3b2b-cd63-474f-9126-167ff91970bc.png)
