### ISSUE TITLE
Let Events Organisers view events that a user is signed up to.

### ISSUE THREAD

**Issue by dpoulson** [Droid-Builder-Web-Team/db_mot#195]

**Comment by RobHowdle** [comment]
We could add a section on the users profile in a collapsable tab for "Upcoming Events" which can list all the events that user has signed up too. No harm in the actual user being able to see that at a quick glance. Once styling and tidying of the profile is complete this could be a nice addition.

**Comment by dpoulson** [comment]
Yep, sounds good.

**Comment by dpoulson** [comment]
Added functionality in ready for restyle
