### ISSUE TITLE
Quick add location from add events page

### ISSUE THREAD

**Issue by dpoulson** [Droid-Builder-Web-Team/db_mot#54]
Allow an EO to add a new location when they are adding a new event, without leaving the event page (and losing anything already entered) 

Should be ok with just a name and postcode, they can go back later and flesh it out

**Comment by RobHowdle** [comment]
Can we add a partial location form and insert blank data into the locations event to avoid making everything nullable?

**Comment by dpoulson** [comment]
I think just a modal popup with the locations form, and then on a successful submit it forces a refresh on the drop down.

**Comment by RobHowdle** [comment]
We'd still need to insert some blank data to accomodate the fields that are not nullable. Popup Modal shouldn't be an issue though.
