### ISSUE TITLE
Droid Image Upload

### ISSUE THREAD

**Issue by RobHowdle** [Droid-Builder-Web-Team/db_mot#55]
When replacing an image for a droid, the image uploads successfully but until the page is manually refreshed, the new image doesn't show. A typical user will assume the image has not uploaded correctly.

**Comment by dpoulson** [comment]
Can't replicate this. Sounds like a browser cache issue, but working fine on my browser. Tried on both chrome and firefox.

**Comment by RobHowdle** [comment]
[https://drive.google.com/file/d/1nEWHHyAM0QpBT9HmMoZ61bG5E_rl5Mx1/view?usp=sharing]

Upon uploading new image, Image Success alert is now present, didn't see it previously however video shows this bug of the physical image not changing. Video also shows cache being cleared.
