### ISSUE TITLE
Let members request events.

### ISSUE THREAD

**Issue by RobHowdle** [Droid-Builder-Web-Team/db_mot#57]
Way for members to request events. Specific form for new event requests requiring members to fill out detailed forms that get sent to event organisers to review and contact the member/ venue to discuss.

**Comment by dpoulson** [comment]
Added section at the bottom of the upcoming events page describing how to submit an event.

Maybe link to the form on the main website too?

**Comment by dpoulson** [comment]
Updated the form on the main website to force entry of various info, etc.
