### ISSUE TITLE
Submit Interest on Event

### ISSUE THREAD

**Issue by RobHowdle** [Droid-Builder-Web-Team/db_mot#83]
When submitting interested, it shows a bullet point but the users name doesn't seem to show.

**Comment by RobHowdle** [comment]
![Bug1`](https://user-images.githubusercontent.com/43747640/95001377-52264980-05c1-11eb-8296-7729af0c5e9a.jpg)

**Comment by dpoulson** [comment]
The usernames are there, the styling is wrong on <ul> tags
